### ISSUE TITLE
[BUG] Worker fails to fallback to JavaScript solver when WASM is available but not fully supported

### ISSUE THREAD

**Issue by izanhzh** [tiagorangel1/cap#89]
**Describe the bug**
In certain older browsers (e.g., Chrome 86), WebAssembly is reported as supported but some WASM features may not be fully implemented. When the WASM solver fails in these environments, the system logs the message "[cap worker] using fallback solver due to error:", but does not actually fallback to the JavaScript solver, causing the CAPTCHA solving process to fail completely.

**Affects:**
- [] Standalone mode
- [x] Widget
- [] Server
- [] WASM
- [] Solver
- [] Solver CLI

**To Reproduce**
1. Use an older browser with partial WASM support (e.g., Chrome 86)
2. Attempt to solve a CAPTCHA challenge
3. Observe that WASM loading or execution fails
4. Check console logs for "[cap worker] using fallback solver due to error:" message
5. Note that the fallback JavaScript solver is not actually triggered

**Expected behavior**
When WASM is available but fails during loading or execution, the worker should properly fallback to the JavaScript-based solver implementation.

**Screenshots**
<img width="1200" height="307" alt="Image" src="https://github.com/user-attachments/assets/3b1296ee-0b47-4cbd-93f7-dc2205adde51" />

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [86]

**Additional context**
This issue affects users on older browsers that claim to support WASM but don't have complete implementation, potentially blocking them from completing CAPTCHA challenges entirely.

**Comment by tiagozip** [comment]
fixed by widget@0.1.26

**Comment by izanhzh** [comment]
@tiagorangel1  Still having issues with v0.1.26. I think the code logic shown below is problematic -  it might not re-enter the if block

<img width="737" height="462" alt="Image" src="https://github.com/user-attachments/assets/996746c2-4db8-45ed-86af-2d4bd0185890" />

**Comment by pxgo** [comment]
Same issue.
@cap.js/widget: v0.1.30
@cap.js/server: v4.0.3

<img width="1235" height="605" alt="Image" src="https://github.com/user-attachments/assets/388a6df1-dd77-4745-9bf9-f48826b317e4" />

**Comment by tiagozip** [comment]
mind sharing a github repo or codesandbox reproducing the error so i can look into your specific case further?

**Comment by pxgo** [comment]
> mind sharing a github repo or codesandbox reproducing the error so i can look into your specific case further?

Here is a minimal example of using Cap.js with the Express framework: https://github.com/pxgo/capjs-demo
To reproduce the issue, you can install Chrome 86.0.4240.111 in a system sandbox for testing. Recommended Chrome download link: https://github.com/dengcao/chrome/tree/main/windows/64Bit.

**Comment by tiagozip** [comment]
it seems to work perfectly fine, both with and without wasm enabled, on chrome and firefox.

<img width="942" height="700" alt="Image" src="https://github.com/user-attachments/assets/e5a52aec-0416-4fce-9bb9-d116595f9924" />

<img width="1081" height="486" alt="Image" src="https://github.com/user-attachments/assets/06c244b1-5c4e-4169-a037-c0bbdd85a4f6" />

**Comment by izanhzh** [comment]
@tiagozip Are you using the browser version mentioned in @pxgo  comment? If WASM is completely disabled, there's no problem. However, some older browser versions support WASM but lack certain features, which causes the code execution to reach the following section.

```js
	self.onmessage = async ({ data: { salt, target, wasmUrl } }) => {
		let fb;

		if (wasmCacheUrl !== wasmUrl) {
			wasmCacheUrl = wasmUrl;
			await import(wasmUrl)
				.then((wasmModule) => {
					return wasmModule.default().then((instance) => {
						solve_pow_function = (
							instance?.exports ? instance.exports : wasmModule
						).solve_pow;
					});
				})
				.catch((e) => {
					console.error("[cap worker] using fallback solver due to error:", e);
					fb = true;

					return solveFallback({ salt, target });
				});

			if (fb) return;
		}
```

Please pay attention to the condition `if (wasmCacheUrl !== wasmUrl)`. Depending on the challenge difficulty setting, this will be executed many times. It works normally for the first `solveFallback`, but on the second attempt, it will skip this if condition.

**Comment by pxgo** [comment]
> it seems to work perfectly fine, both with and without wasm enabled, on chrome and firefox.
> 
> <img alt="Image" width="942" height="700" src="https://private-user-images.githubusercontent.com/70700766/505269104-e5a52aec-0416-4fce-9bb9-d116595f9924.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIxMzg3MjMsIm5iZiI6MTc2MjEzODQyMywicGF0aCI6Ii83MDcwMDc2Ni81MDUyNjkxMDQtZTVhNTJhZWMtMDQxNi00ZmNlLTliYjktZDExNjU5NWY5OTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTAzVDAyNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNGZjNTZkMjMzZDQ0Y2U1MjVmZTRiNzk2Mzg0MTUxNzRjMGIwNzc4OTQ0MTlhOGVhZDRkZjQ3ODUyNjJiMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7gz9-S5G5JRhf0tpggtBEpG20TvsHyjPNwu_PRLMFXo"> <img alt="Image" width="1081" height="486" src="https://private-user-images.githubusercontent.com/70700766/505269777-06c244b1-5c4e-4169-a037-c0bbdd85a4f6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIxMzg3MjMsIm5iZiI6MTc2MjEzODQyMywicGF0aCI6Ii83MDcwMDc2Ni81MDUyNjk3NzctMDZjMjQ0YjEtNWM0ZS00MTY5LWEwMzctYzBiYmRkODVhNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTAzVDAyNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NGZiZjc3MWUxNmJhZmMxZDg2NGU5NDg5N2NiNmFmZWNjM2IxZTk0MmRlNGU1NjMwODgzMzA3NTNlMWY5NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i647wa59-jF-UR5z8Gd1GgKtZv88W-DNNJ1N8lM0Q2I">

What version of browser are you using? I can stably reproduce the issue in Chrome 86.0.4240.111.

**Comment by tiagozip** [comment]
ill look into it
